### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by daniel-cmorales** [Johann-S/bs-stepper#151]
Thanks for your plugin.

I don't use bs-stepper with cdn link. I downloaded the files and saved it in my foolder. But I saw an error in the console web. I tried to using jQuery and JS Vanilla, comment that line code, but it doesn't fix. I haven't modified anything more.

![error-bs-stepper](https://user-images.githubusercontent.com/48781211/77565558-02d0c500-6e8a-11ea-86b7-f31f5fb51e84.jpg)

**Comment by admirhusic** [comment]
I think you can close this issue. 
I had the same problem but realized that I had the wrong order in loading the scripts.

**Comment by Johann-S** [comment]
Hi @DanielCMorales,

It seems related on how you're using `bs-stepper`, I can't help you more than that without a bit of your code

**Comment by hamlet237** [comment]
Hi there Johann-S. I´m facing the same problem here. 
![imagen](https://user-images.githubusercontent.com/5007142/79065888-f505a700-7cb3-11ea-86f7-b23c386923d9.png)

I´m working under WP framework. Here is my code:
You can see dependencies here:
view-source:https://smrc.dev.bjaland.co/training/trainee-panel/?smrc_training_id=3782

HTML + PHP:
`<h2 class="smrc-title"><?php echo get_the_title(get_post_meta($smrc_training_id, 'smrc_training_related_event', true)); ?></h2>

<div class="bs-stepper smrc-steps">
  <div class="bs-stepper-header" role="tablist">
    <div class="step" data-target="#logins-part">
      <button type="button" class="step-trigger" role="tab" aria-controls="logins-part" id="logins-part-trigger">
        <span class="bs-stepper-circle">1</span>
        <span class="bs-stepper-label"><?php _e('Instructions', 'almazen'); ?></span>
      </button>
    </div>

    <div class="line"></div>

    <div class="step" data-target="#information-part">
      <button type="button" class="step-trigger" role="tab" aria-controls="information-part" id="information-part-trigger">
        <span class="bs-stepper-circle">2</span>
        <span class="bs-stepper-label"><?php _e('Homework', 'almazen'); ?></span>
      </button>
    </div>

    <div class="line"></div>

    <div class="step" data-target="#information-part">
      <button type="button" class="step-trigger" role="tab" aria-controls="information-part" id="information-part-trigger">
        <span class="bs-stepper-circle">3</span>
        <span class="bs-stepper-label"><?php _e('Webinar', 'almazen'); ?></span></span>
      </button>
    </div>

    <div class="line"></div>

    <div class="step" data-target="#information-part">
      <button type="button" class="step-trigger" role="tab" aria-controls="information-part" id="information-part-trigger">
        <span class="bs-stepper-circle">4</span>
        <span class="bs-stepper-label"><?php _e('Certificate', 'almazen'); ?></span></span>
      </button>
    </div>
  </div>

  <div class="bs-stepper-content">
    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
      <p><?php _e('Instructions for training', 'almazen'); ?> <?php echo get_the_title(get_post_meta($smrc_training_id, 'smrc_training_related_event', true)); ?></p>
    </div>

    <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger">
        
      <div class="smrc-sub-step-videos mb-50">
        <h4 class="text-align-center"><?php _e('Training Videos', 'almazen'); ?></h4>

        <?php if(empty(get_post_meta($smrc_training_id, 'smrc_training_related_videos'))) {
          echo do_shortcode('[smrc-call-to-action smrc_call_to_action_icon="assignment_late" smrc_call_to_action_title="No videos found" smrc_call_to_action_content="Oppsss! We haven´t found any video associated with this training"]');
        }else{ 
          if (empty(get_user_meta($smrc_user_id, 'smrc_trainer_training_video_finished', true)[$smrc_training_id])) { echo do_shortcode('[smrc-call-to-action smrc_call_to_action_icon="assignment_late" smrc_call_to_action_title="Videos not shown" smrc_call_to_action_content="You have not seen all the training videos. Please complete the viewing of all the proposed videos."]');
          }else{ 
            echo do_shortcode('[smrc-call-to-action smrc_call_to_action_icon="assignment_turned_in" smrc_call_to_action_title="Videos shown" smrc_call_to_action_content="Hooray! You have completed the viewing of all the proposed videos</a>"]');
          } ?>

          <div class="row">
          <?php foreach (get_post_meta($smrc_training_id, 'smrc_training_related_videos', true) as $video_key => $video_url) { ?>
            <div class="col-md-4 text-align-center">
              <div>
                <div class="smrc-training-video-watch-btn" data-smrc-video-watched="false">
                  <p class="color-white mt-40 mb-10">Video <?php echo ($video_key + 1); ?></p>
                  <i class="material-icons font-size-50 color-white">play_circle_outline</i>
                </div>
              </div>
              <?php echo wp_oembed_get($video_url);; ?>
            </div>
          <?php } ?>
          </div>
        <?php } ?>
      </div>

      <div class="smrc-sub-step-homework mb-50">
        <h4 class="text-align-center"><?php _e('Training Homework', 'almazen'); ?></h4>
        <?php if (empty(get_user_meta($smrc_user_id, 'smrc_trainer_training_homework_finished', true)[$smrc_training_id])) { ?>
          <p><?php _e('', 'almazen'); ?></p>
          <?php echo do_shortcode('[smrc-call-to-action smrc_call_to_action_icon="assignment_late" smrc_call_to_action_title="Homework not received" smrc_call_to_action_content="You still haven\'t turned in the homework</a>"]'); ?>
          <div class="text-align-center margin-auto">
            <a href="#" class="smrc-btn smrc-training-homework-finish-btn"><?php _e('Send now', 'almazen'); ?></a><img class="smrc-waiting" style="display:none;" src="/wp-content/uploads/2019/07/ajax-loader.gif" alt="<?php _e('loading from SMRC...', 'almazen'); ?>"/>
          </div>
        <?php }else{ 
          echo do_shortcode('[smrc-call-to-action smrc_call_to_action_icon="assignment_turned_in" smrc_call_to_action_title="Homework received" smrc_call_to_action_content="Hooray! You have turned in the homework</a>"]');
        } ?>
      </div>
    </div>

    <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger">
      <?php echo do_shortcode('[smrc-webinar smrc_webinar_id="6470370634"]'); ?>
    </div>

    <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger">
      <p>More things here.</p>
    </div>
  </div>
</div>`

JQUERY
`<script>
  jQuery(document).ready(function($) {
    var smrc_stepper = new Stepper($('.bs-stepper'));
  });
</script>`

Thanks in advance!

**Comment by hamlet237** [comment]
Something was wrong formatting the code. I attach the complete 
[bs-steps.txt](https://github.com/Johann-S/bs-stepper/files/4466126/bs-steps.txt)
function in txt.

**Comment by leandroruel** [comment]
same here

**Comment by Johann-S** [comment]
@hamlet237 and @leandroruel 

This error means you pass something `null` to `bs-stepper` or you don't follow the needed structure 😟 

I would love to see a live demo of the problem, please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.

Without that, I can't confirmed it's related to the libs, and it seems related to how you're using `bs-stepper`

**Comment by diegoibanezr** [comment]
I'm having this issue too trying to use it with vuejs, any solution?
`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'classList' of null"`

**Comment by leandroruel** [comment]
I'll try this later, maybe not today as i have a lot of work here to do.

**Comment by Johann-S** [comment]
I'm still waiting for your live demo of the problem on [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/).

**Comment by kingraphaii** [comment]
@Johann-S here is the link to a pen I made: [https://codepen.io/kingraphaii/pen/mdPeNRP](https://codepen.io/kingraphaii/pen/mdPeNRP)

**Comment by buncis** [comment]
`Uncaught TypeError: Cannot read property 'classList' of null` also means that

 the selector cannot find a html object with `bs-stepper` class

please recheck the html where you load the script is it contain a html object with `bs-stepper` class

**Comment by iamtekson** [comment]
Is there any update on this issue? I am still getting the same issue. I tried to implement it on a `React`.

**Comment by schmetti-dev** [comment]
I got the error as long as the bs-stepper-content didn't have all data-targets from the bs-stepper-header as a div id

So you need a div with a corresponding ID for exactly every data target.
For example, as long as you have 5 steps in the header and 4 or 6 in the content, the error occurs

**Comment by hrvalizad** [comment]
> I got the error as long as the bs-stepper-content didn't have all data-targets from the bs-stepper-header as a div id
> 
> So you need a div with a corresponding ID for exactly every data target. For example, as long as you have 5 steps in the header and 4 or 6 in the content, the error occurs

same problem and this solution worked. Thanks.
