### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ziguane** [Johann-S/bs-stepper#16]
Hi,

What solutions do you recommend for the validation of the form ?

**Comment by ziguane** [comment]
Hi @Johann-S,

Parsleyjs is well documented for multi steps forms validation, on the other hand with bootstrap it seems less obvious... I'll look, but if you have an example, I'd like to see that.

In any case, thank you and congratulations for this project.

**Comment by ziguane** [comment]
Thanks for the example

I imagined a slightly different solution.
Validation at each step. Without possibility to proceed to the next step without validation.
I'll try with parsleyjs

Yes an example of validation in the documentation can be great
Thanks again

**Comment by Johann-S** [comment]
I think it's totally doable too 👍 

you're welcome 👍

**Comment by Johann-S** [comment]
Hi @ziguane since v1.5.0 bs-stepper emit two events see: https://github.com/Johann-S/bs-stepper#events

With that, you'll be able to stop the switch to the next step if your form is not valid

**Comment by Johann-S** [comment]
I added an example here: https://bs-stepper.netlify.com/

I'll publish a new release soon 👍
