### ISSUE TITLE
bs_stepper_1.default is not a constructor

### ISSUE THREAD

**Issue by nithya-ramesh** [Johann-S/bs-stepper#167]
I am trying to use bs-stepper in my angular application. Referred to https://stackblitz.com/edit/bs-stepper-angular?file=src%2Fapp%2Fapp.component.ts
However i get the error related to constructor. Any pointers on how to solve this?

**Comment by Johann-S** [comment]
Hi @nithya-ramesh,

You have to be sure in your `tsconfig.json` you have that:
```json
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}

**Comment by nithya-ramesh** [comment]
thanks a lot @Johann-S it work fine now!
