### ISSUE TITLE
Docs not working, missing files

### ISSUE THREAD

**Issue by oleteacher** [Johann-S/bs-stepper#20]
Thought you may like to know that your docs example is broken and seem to be missing the main.js.

There is no /dist folder?

Cheers!

**Comment by oleteacher** [comment]
I mean the docs in the zip downloaded from GitHub. If I download it and try the docs, then do not work correctly. Perhaps that is how you mean the layout to be though.

**Comment by Johann-S** [comment]
Oh yeah, if you want to run the documentation locally, you have to do:

```shell
npm install
```

and
```
npm run build && npm run docs-build && npm run docs-serve
```

**Comment by oleteacher** [comment]
Thanks!

**Comment by Johann-S** [comment]
you're welcome 👍
