### ISSUE TITLE
ANGULAR 7 issues

### ISSUE THREAD

**Issue by ErwinBustillo** [Johann-S/bs-stepper#22]
I'm using this library on my own angular 7 project with 3 reactive forms 

so the problem is when I initialized the stepper variable on init hook and call next void in a button to enable the following form the console log throw this error: 
ERROR TypeError: Cannot read property 'classList' of null
    at bs-stepper.js:135
    at Array.filter (<anonymous>)
    at showContent (bs-stepper.js:134)
    at new Stepper (bs-stepper.js:259)
    at RequestComponent.push../src/app/pages/request/request.component.ts.RequestComponent.next (request.component.ts:81)
    at Object.eval [as handleEvent] (RequestComponent.html:134)
    at handleEvent (core.js:23008)
    at callWithDebugContext (core.js:24078)
    at Object.debugHandleEvent [as handleEvent] (core.js:23805)
    at dispatchEvent (core.js:20457)

COULD YOU HELP ME  to solved this?

**Comment by Johann-S** [comment]
Hi @ErwinBustillo,

Sure, can you share how you use bsStepper on your component typescript file ?
BTW I shared this example of how to use bsStepper on Angular see: https://stackblitz.com/edit/bs-stepper-angular

**Comment by ErwinBustillo** [comment]
this is my request component ts :

import { Subscription } from 'rxjs';
import { ApiService } from './../../services/api.service';
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormGroup, FormBuilder, Validators, FormArray, FormControl } from
'@angular/forms';
import { atLeastOne } from './../../utilities/validations';
import Stepper from 'bs-stepper';

import * as $ from 'jquery';

import Swal from 'sweetalert2';


@Component({
selector: 'app-request',
templateUrl: './request.component.html',
styleUrls: ['./request.component.css']
})
export class RequestComponent implements OnInit,OnDestroy {

form1: FormGroup;
form2: FormGroup;
form3: FormGroup;

departments:any[] = [];
periods:any[] = [];
hidef1:boolean = false;
hidef2:boolean = true;
hidef3: boolean = true;
hidef4:boolean = true;
private subs:Subscription;
private step:Stepper;

anterior:number = 0;
siguiente:number = 1;

constructor(private fb: FormBuilder, private api:ApiService) {

this.form1 = this.fb.group({
department: this.fb.control('', Validators.required),
period: this.fb.control('', Validators.required),
credits: this.fb.control(0,Validators.required),
name: this.fb.control('',Validators.required),
nrcs: this.fb.array([''], atLeastOne(Validators.required))
});

this.form2 = this.fb.group({
ra: this.fb.array([''],atLeastOne(Validators.required))
});

this.form3 = this.fb.group({
magistral: this.fb.control('false', Validators.required),
qcds: this.fb.array([], atLeastOne(Validators.required))
});

}

ngOnInit() {
// $(document).ready(()=> this.step = new Stepper($('.bs-stepper')[0]));
this.subs = this.api.getAllDepartments().subscribe((data:any)=> {

this.departments = data.departments
this.form1.get('department').setValue(this.departments[0]._id);
});
this.api.getAllVisiblePeriods().subscribe((data:any)=> {
this.periods = data.periods;
this.form1.get('period').setValue(this.periods[0].name)
});
}

ngOnDestroy(){
this.subs.unsubscribe();
this.departments = [];
this.periods = [];
}

next(){
if (this.siguiente == 3) {
this.anterior = this.siguiente;
this.siguiente += 1;
this.hidef3 = true;
this.hidef4 = false;

}else{
if (this.siguiente == 2) {
this.anterior = this.siguiente;
this.siguiente += 1;
this.hidef2 = true;
this.hidef3 = false;
//CREATE FOR EACH NRC ARRAY OF QCD
let arr = this.form3.get('qcds') as FormArray;
if (this.form3.get('magistral').value == 'false' && arr.length == 0) {
this.generateQCDArray();
}
}else{
if(this.siguiente == 1){
this.anterior = this.siguiente;
this.siguiente += 1;
this.hidef1 = true;
this.hidef2 = false;
}
}
}

}

previous(){

if (this.anterior == 3) {
this.siguiente = this.anterior;
this.anterior -= 1;
this.hidef3 = false;
this.hidef4 = true;

}
else{
if (this.anterior == 2) {
this.siguiente = this.anterior;
this.anterior -= 1;
this.hidef2 = false;
this.hidef3 = true;
}else{
if(this.anterior == 1){
this.siguiente = this.anterior;
this.anterior -= 1;
this.hidef1 = false;
this.hidef2 = true;
}
}
}
}

//HANDLER NRC COURSES
addNRC(){
let array = this.form1.get('nrcs') as FormArray;
array.push(new FormControl('', Validators.required));
}

removeNRC(index:number){
let array = this.form1.get('nrcs') as FormArray;
array.removeAt(index);
}

//HANDLER LEARNING RESULTS
addRA(){
let array = this.form2.get('ra') as FormArray;
array.push(new FormControl('', Validators.required));
}

removeRA(index:number){
let array = this.form2.get('ra') as FormArray;
array.removeAt(index);
}

//QCD CREATION METHODS HANDLER

onChangeCheck(event:any){
console.log(event.target.checked);
if (event.target.checked) {
this.form3.get('magistral').setValue('true');
if (this.form3.contains('qcds')) {
this.form3.removeControl('qcds');
}
this.form3.addControl('qcd',this.fb.group({
application_date: this.fb.control('', Validators.required),
//hour: this.fb.control('', Validators.required),
place: this.fb.control('', Validators.required),
students: this.fb.control(0,Validators.required)
}));
console.log(this.form3.get('qcd'));
}else{
this.form3.get('magistral').setValue('false');
if (this.form3.contains('qcd')) {
this.form3.removeControl('qcd');
}
this.form3.addControl('qcds',this.fb.array([]));
this.generateQCDArray(); // call generate array of qcds
}

}

generateQCDArray(){
let array = this.form3.get('qcds') as FormArray;
let nrc_array = this.form1.get('nrcs') as FormArray;
for (let index = 0; index < nrc_array.length; index++) {
array.push(this.fb.group({
application_date: this.fb.control('', Validators.required),
//hour: this.fb.control('', Validators.required),
place: this.fb.control('', Validators.required),
students: this.fb.control(0,Validators.required)
}));
}
}

submit(){
console.log('FORMA 1', this.form1.value);
console.log('FORMA 2', this.form2.value);
console.log('FORMA 3', this.form3.value);

if (this.form1.invalid || this.form2.invalid || this.form3.invalid) {
return true;
}

Swal.fire({
title: 'Estas seguro?',
text: "Puede que al eliminarse este departamento algunos profesores y
cursos queden sin un departamento asociado",
type: 'warning',
showCancelButton: true,
confirmButtonColor: '#3085d6',
cancelButtonColor: '#d33',
cancelButtonText: 'No',
confirmButtonText: 'Si'
}).then((result) => {
if (result.value) {
console.log('LISTO PARA SUBIR');
}
});

}

}


THIS IS MY REQUEST COMPONENT HTML:
<div class="row">
<div class="col-md-12">
<div class="card">
<div class="card-body">
<h3>Solicitud de QCD</h3>
<hr>
<br>
<div id="stepper1" class="bs-stepper linear">
<div class="bs-stepper-header" role="tablist">
<div class="step" [ngClass]="{'active': hidef1 == false}" data-target=
"#test-l-1">
<button type="button" class="btn btn-link step-trigger" role="tab"
aria-controls="test-l-1" aria-selected="true">
<span class="bs-stepper-circle">1</span>
<span class="bs-stepper-label">CREACION DE CURSO</span>
</button>
</div>
<div class="line"></div>
<div class="step" [ngClass]="{'active': hidef2 == false}" data-target=
"#test-l-2">
<button type="button" class="btn btn-link step-trigger" role="tab"
aria-controls="test-l-2" aria-selected="false" disabled="disabled">
<span class="bs-stepper-circle">2</span>
<span class="bs-stepper-label">DESCRIPCION DE LOS R.A</span>
</button>
</div>
<div class="line"></div>
<div class="step" [ngClass]="{'active': hidef3 == false}" data-target=
"#test-l-3">
<button type="button" class="btn btn-link step-trigger" role="tab"
aria-controls="test-l-3" aria-selected="false" disabled="disabled">
<span class="bs-stepper-circle">3</span>
<span class="bs-stepper-label">SOLICITUD QCD</span>
</button>
</div>
<div class="line"></div>
<div class="step" [ngClass]="{'active': hidef4 == false}" data-target=
"#test-l-4">
<button type="button" class="btn btn-link step-trigger" role="tab"
aria-controls="test-l-4" aria-selected="false" disabled="disabled">
<span class="bs-stepper-circle">4</span>
<span class="bs-stepper-label">CONFIRMACION</span>
</button>
</div>
</div>
<div class="bs-stepper-content">

<form [ngClass]="{'active': hidef1 == false}" class="content" [formGroup]=
"form1" id="test-l-1" role="tabpanel">
<div class="form-group">
<legend class="col-form-label">Nombre</legend>
<input formControlName="name" type="text" class="form-control col-sm-6"
placeholder="Nombre del curso" />
</div>
<div class="form-group">
<legend class="col-form-label">Departamento</legend>
<select formControlName="department" class="form-control col-sm-6">
<option *ngFor="let d of departments" [value]="d._id">{{d.name}}</option>
</select>
</div>
<div class="form-row" formArrayName="nrcs">
<div class="col-md-4" >
<legend class="col-form-label">NRC</legend>
<div *ngFor="let n of form1.get('nrcs')?.controls; let i=index" >
<div class="row">
<div class="col-md-4">
<input [formControlName]="i" type="text" minlength="4" maxlength="4" class=
"form-control" placeholder="####"/>
</div>
<div class="form-row">
<div class="col-md-6">
<button class="btn btn-success" (click)="addNRC()">+</button>
</div>
<div class="col-md-4">
<button *ngIf="i > 0" class="btn btn-danger" (click)="removeNRC(i)">-</
button>
</div>
</div>
</div>
<br>
</div>
</div>
</div>
<br>
<div class="form-row">
<div class="col-md-4">
<legend class="col-form-label">Periodo</legend>
<select formControlName="period" type="text" class="form-control col-sm-4" >
<option *ngFor="let p of periods" [value]="p.name">{{p.name}}</option>
</select>
</div>
<div class="col-md-2">
<legend class="col-form-label">Creditos</legend>
<input formControlName="credits" type="number" class="form-control" min="1"
max="5" value="1"/>
</div>
</div>
<br>
<hr>
<div class="container text-right">
<button type="button" class="btn btn-primary" (click)="next()" [disabled]=
"form1.invalid">Siguiente</button>
</div>
</form>


<form [ngClass]="{'active': hidef2 == false}" [formGroup]="form2" id=
"test-l-2" role="tabpanel" class="content">
<legend class="text-left">Curso: {{form1.get('name').value}}</legend>
<hr>
<br>
<div class="text-justify">
<p class="pt-0">
A continuación, escriba los resultados de aprendizaje que se han trabajado
hasta ahora en su curso. Procure redactarlos de forma clara y específica
para que el estudiante los comprenda fácilmente, puesto que éste deberá
evaluarlos durante la implementación del QCD.
</p>
<p>
<strong>Por ejemplo: </strong> Identificar los diferentes tipos de escalas
de medición en el diseño de planos arquitectónicos.
No es necesario que llene todos los espacios, solo el número de resultados
de aprendizaje que usted considere trabajados hasta ahora.
</p>
</div>

<div class="form-row" formArrayName="ra">
<div class="col-md-12" >
<legend class="col-form-label">Resultados de Aprendizaje: </legend>
<div *ngFor="let r of form2.get('ra')?.controls; let i=index" >
<div class="row">
<div class="col-md-4">
<input [formControlName]="i" type="text" class="form-control" placeholder=
"Aprendizaje...."/>
</div>
<div class="form-row">
<div class="col-md-6">
<button class="btn btn-success" (click)="addRA()">+</button>
</div>
<div class="col-md-4">
<button *ngIf="i > 0" class="btn btn-danger" (click)="removeRA(i)">-</button
>
</div>
</div>
</div>
<br>
</div>
</div>
</div>
<br>
<hr>
<div class="row">
<div class="col-md-6 text-left">
<button class="btn btn-primary" (click)="previous()">Anterior</button>
</div>
<div class="col-md-6 text-right">
<button class="btn btn-primary" (click)="next()" [disabled]="form2.invalid">
Siguiente</button>
</div>
</div>
</form>


<form id="test-l-3" [ngClass]="{'active': hidef3 == false}" class="content"
role="tabpanel" [formGroup]="form3" >
<legend class="text-left">Curso: {{ form1.get('name').value }}</legend>
<hr>
<br>
<div class="form-row">
<label class="col-form-label">¿Esta solicitud para los NRC: <span *ngFor="let
n of form1.get('nrcs').controls">{{n.value}},</span> se realizará en una
misma aplicación (mismo lugar y hora)?</label>
<input type="checkbox" class="form-control" (change)="onChangeCheck($event)"
/>
</div>
<br>
<div *ngIf="form3.contains('qcd')">
<div class="form-row" formGroupName="qcd">
<div class="col-md-4">
<label class="col-form-label">Fecha de Aplicacion</label>
<input type="date" class="form-control" formControlName="application_date"
placeholder="Fecha" />
</div>
<div class="col-md-4">
<label class="col-form-label">Lugar</label>
<input type="text" class="form-control" formControlName="place"
placeholder="Ejemplo
25K" />
</div>
<div class="col-md-4">
<label class="col-form-label"># Estudiantes</label>
<input type="text" class="form-control" formControlName="students"
placeholder="Digite el numero de estudiantes" />
</div>
</div>
</div>

<div formArrayName="qcds">
<div class="container" *ngFor="let q of form3.get('qcds')?.controls; let
i=index">
<div [formGroupName]="i" class="card card-body">
<div class="card-header">
NRC: {{form1.get('nrcs').value[i]}}
</div>

<div class="form-row">
<div class="col-md-4">
<label class="col-form-label">Fecha de Aplicacion</label>
<input type="date" class="form-control" formControlName="application_date"
placeholder="Fecha" />
</div>
<div class="col-md-4">
<label class="col-form-label">Lugar</label>
<input type="text" class="form-control" formControlName="place"
placeholder="Ejemplo
25K" />
</div>
<div class="col-md-4">
<label class="col-form-label"># Estudiantes</label>
<input type="text" class="form-control" formControlName="students"
placeholder="Digite el numero de estudiantes" />
</div>
</div>
</div>
</div>
</div>

<hr>
<br>
<div class="row">
<div class="col-md-6 text-left">
<button class="btn btn-primary" (click)="previous()">Anterior</button>
</div>
<div class="col-md-6 text-right">
<button class="btn btn-primary" (click)="next()" [disabled]="form3.invalid">
Siguiente</button>
</div>
</div>

</form>


<form id="test-l-4" [ngClass]="{'active': hidef4 == false}" class="content"
role="tabpanel" >
<legend class="text-left">Curso: {{form1.get('name').value}}</legend>
<br>
<legend class="text-left">NRC:</legend>
<p *ngFor="let n of form1.get('nrcs').controls" class="text-left">
{{n.value}}</p>
<br>
<legend class="text-left">Periodo: {{ form1.get('period').value}}</legend>
<br>
<legend class="text-left">Resultados de Aprendizaje: </legend>
<p *ngFor="let r of form2.get('ra').controls" class="text-left">{{r.value}}
</p>
<br>
<legend class="text-left">Tipo Magistral:
<span *ngIf="form3.get('magistral').value == 'false'">NO</span>
<span *ngIf="form3.get('magistral').value == 'true'">SI</span>
</legend>
<hr>
<br>
<div class="row">
<div class="col-md-6 text-left">
<button class="btn btn-primary" (click)="previous()">Anterior</button>
</div>
<div class="col-md-6 text-right">
<button class="btn btn-primary" (click)="submit()">Confirmar</button>
</div>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>

**Comment by Johann-S** [comment]
According to your issue, it seems `.bs-stepper` isn't found in your template file

**Comment by ErwinBustillo** [comment]
Because i had to removed it I had to managed the active process with
ngclass for to next and previous issue with stepper

**Comment by Johann-S** [comment]
I don't understand why you're not using bs-stepper next and previous methods 🤔

If you remove totally the stepper or the steps that's normal it doesn't work.

Can you show me your code on a Stackblitz ?

**Comment by ErwinBustillo** [comment]
It's difficult because is a big app with multiple section routes and api

**Comment by Johann-S** [comment]
Ok, so currently I cannot help you more than that. 
I ask for a reduce test case on Stackblitz with not API calls just an example of your issue.
You did a Copy/Paste of your code without formatting it, which lead to something not readable.

Why do you manage yourself active steps ? You have `bs-stepper` methods for that `next` and `prev` and `to`

**Comment by Johann-S** [comment]
Closing due to the lack of answers.

Feel free @ErwinBustillo to comeback with a live demo of your problem
