### ISSUE TITLE
Important style issues

### ISSUE THREAD

**Issue by scrnjakovic** [Johann-S/bs-stepper#23]
Since there are rules defined as:
```css
.bs-stepper a
```
This messes all the links inside the `.bs-stepper`.

All `.bs-stepper a` references should be removed and should only target `.step-trigger`

**Comment by Johann-S** [comment]
Hi @scrnjakovic,

Yes I understand your issue, this selector is remaining from the first release.
We'll fix that a draft a new release with a breaking change note.

Thanks for using bs-stepper 👍

/CC @MartijnCuppens if you want to tackle that 👼

**Comment by Johann-S** [comment]
I'll draft a release today 👍

**Comment by Johann-S** [comment]
@scrnjakovic released
https://github.com/Johann-S/bs-stepper/blob/master/CHANGELOG.md

**Comment by scrnjakovic** [comment]
@Johann-S thanks for making it available to us! :)
