### ISSUE TITLE
Get an error when using previous method

### ISSUE THREAD

**Issue by 23aryan** [Johann-S/bs-stepper#25]
thanks for your plugin, 
I made this component kinda dynamic and I'm passing different components to it to show, but when I try to use previous function to go back I get this error:

ERROR TypeError: Cannot read property 'classList' of null
    at bs-stepper.js:111
    at Array.forEach (<anonymous>)
    at showStep (bs-stepper.js:107)
    at Stepper.previous (bs-stepper.js:296)

could you please help me to find out how to resolve this issue?
thanks

**Comment by Johann-S** [comment]
Hi @23aryan,

I guess you're using the last release of bs-stepper (1.4.1), this version include a breaking change.
With this version you cannot use `<a>` tag without the class `.step-trigger`.

Please be sure to follow the following HTML markup:
https://github.com/Johann-S/bs-stepper#html-markup

**Comment by 23aryan** [comment]
I'm using 1.4.0 with `<a>`  tag.  should I swap it with buttons and follow the link you sent?

**Comment by Johann-S** [comment]
You can do that, but it's pretty difficult for me to help you without a part of your code, please can you make a reduce test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.

As you can see the previous method works well in the docs: https://johann-s.github.io/bs-stepper/

**Comment by Johann-S** [comment]
Closing due to the lack of answers.

Feel free @23aryan to comeback with a live demo of your problem
