### ISSUE TITLE
Uncaught type error in new version

### ISSUE THREAD

**Issue by nickwilliams999** [Johann-S/bs-stepper#26]
Hi, 

Having a few issues with the new update (using the CDN links), where it will not show the body of the stepper. This seems to also be an issue on the demos here. Any ideas?

The error on the demo page (and similar in my code is):

Uncaught TypeError: Cannot read property 'setAttribute' of null
at util.js:33
at Array.forEach (<anonymous>)
at m (util.js:31)
at new t (index.js:34)
at HTMLDocument.<anonymous> (main.js:5)

Nick

**Comment by trewpog** [comment]
> Hi,
> 
> Having a few issues with the new update (using the CDN links), where it will not show the body of the stepper. This seems to also be an issue on the demos here. Any ideas?
> 
> The error on the demo page (and similar in my code is):
> 
> Uncaught TypeError: Cannot read property 'setAttribute' of null
> at util.js:33
> at Array.forEach ()
> at m (util.js:31)
> at new t (index.js:34)
> at HTMLDocument. (main.js:5)
> 
> Nick

Same error too, switch to the previous version: **1.4.0** to avoid the error.

**Comment by Johann-S** [comment]
Hi :)

As it mentionned in the [CHANGELOG.md](https://github.com/Johann-S/bs-stepper/blob/master/CHANGELOG.md) the last release include a breaking change.

You have to be sure that the child element of your `.step`s elements have the `.step-trigger` class.
Be sure you follow the following HTML markup: https://github.com/Johann-S/bs-stepper#html-markup

The demo use this markup too: https://johann-s.github.io/bs-stepper/

**Comment by nickwilliams999** [comment]
Hey,

Got it working like so:

`					var stepper1 = null

					stepper1 = new Stepper(document.querySelector('#stepper1'), {
						linear: false,
						animation: true
					})`

and then this code...

`	<div id="stepper1" class="bs-stepper">
						<div class="bs-stepper-header" role="tablist">
							<div class="step" data-target="#test-l-1">
								<button type="button" class="step-trigger" role="tab" id="stepper1trigger1"
									aria-controls="test-l-1">
									<span class="bs-stepper-circle">1</span>
									<span class="bs-stepper-label">Email</span>
								</button>
							</div>
							<div class="bs-stepper-line"></div>
							<div class="step" data-target="#test-l-2">
								<button type="button" class="step-trigger" role="tab" id="stepper1trigger2"
									aria-controls="test-l-2">
									<span class="bs-stepper-circle">2</span>
									<span class="bs-stepper-label">Password</span>
								</button>
							</div>
							<div class="bs-stepper-line"></div>
							<div class="step" data-target="#test-l-3">
								<button type="button" class="step-trigger" role="tab" id="stepper1trigger3"
									aria-controls="test-l-3">
									<span class="bs-stepper-circle">3</span>
									<span class="bs-stepper-label">Validate</span>
								</button>
							</div>
						</div>
						<div class="bs-stepper-content">
							<form onSubmit="return false">
								<div id="test-l-1" role="tabpanel" class="bs-stepper-pane"
									aria-labelledby="stepper1trigger1">
									<div class="form-group">
										<label for="exampleInputEmail1">Email address</label>
										<input type="email" class="form-control" id="exampleInputEmail1"
											placeholder="Enter email">
									</div>
									<button class="btn btn-primary" onclick="stepper1.next()">Next</button>
								</div>
								<div id="test-l-2" role="tabpanel" class="bs-stepper-pane"
									aria-labelledby="stepper1trigger2">
									<div class="form-group">
										<label for="exampleInputPassword1">Password</label>
										<input type="password" class="form-control" id="exampleInputPassword1"
											placeholder="Password">
									</div>
									<button class="btn btn-primary" onclick="stepper1.previous()">Previous</button>
									<button class="btn btn-primary" onclick="stepper1.next()">Next</button>
								</div>
								<div id="test-l-3" role="tabpanel" class="bs-stepper-pane text-center"
									aria-labelledby="stepper1trigger3">
									<button class="btn btn-primary mt-5" onclick="stepper1.previous()">Previous</button>
									<button type="submit" class="btn btn-primary mt-5">Submit</button>
								</div>
							</form>
						</div>
					</div>
`
