### ISSUE TITLE
still getting Uncaught TypeError: Cannot read property 'addEventListener' of null     at index.js:52

### ISSUE THREAD

**Issue by rahimimo** [Johann-S/bs-stepper#30]
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at index.js:52

Although there is a closed ticket but I am still getting it using the latest settings.

**Comment by Johann-S** [comment]
Hi @rahimimo,

First of all thanks for using my stepper 👍 

Can you share your stepper HTML, and the javascript you use to init your stepper ? 

And if it's possible, can you create a live demo of the problem, using [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link

**Comment by rahimimo** [comment]
Hi 
Thanks forresponsing I think it was a personal mistake. I close the ticket.

**Comment by danilloestrela** [comment]
Could you please share with us the personal solution you got? Would be nice!
