### ISSUE TITLE
Small screens

### ISSUE THREAD

**Issue by AntoinedeChassey** [Johann-S/bs-stepper#49]
Hi,
How do you render the stepper header to fit in one line for mobile screens ?
In your demo it renders fine because there are only 3 steps.
Thanks for your help,
Antoine

**Comment by Johann-S** [comment]
Hi @AntoinedeChassey,

If you have a huge stepper my suggestion is to use it in vertical mode when you're on small mobile screens, for that you can add the `vertical` css class to your stepper

**Comment by AntoinedeChassey** [comment]
Hi @Johann-S,
Nice thanks !
I'll check this out :)
For now, I ended up only showing the current step for mobile display..
Closing !
Cheers
