### ISSUE TITLE
This.stepper.to is not a function

### ISSUE THREAD

**Issue by himanshukadyan** [Johann-S/bs-stepper#53]
On tab click, bs-stepper is throwing error "this.stepper.to is not a function".
This issue only occurs in the Qa and Production Environment on azure.
I am currently using angular 7 with bs-stepper  "version": "1.5.0".
We have applied a temporary fix by setting "build optimizer": false in agular.json.
Please provide a correct solution for it

**Comment by Johann-S** [comment]
Hi @himanshukadyan,

Thanks for using `bs-stepper` 👍 

I would love to help you but I cant without a live example of your issue 😟 
Please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.
