### ISSUE TITLE
Error on initializing stepper

### ISSUE THREAD

**Issue by lcsqlpete** [Johann-S/bs-stepper#57]
I'm getting error "Cannot read property 'classlist' of null" on the line that creates a stepper instance.  My code is:

<pre>
$(document).ready(function () {
    var stepper = new Stepper($('.bs-stepper')[0])
})
</pre>

There is a div with class bs-stepper on the page.  The stepper is within a bootstrap modal in case that matters.

**Comment by lcsqlpete** [comment]
Never mind, fixed it.

**Comment by sky7st** [comment]
I have the same issue but I am using vue.js.
Could you tell me how to fix the bug?

**Comment by sky7st** [comment]
> Never mind, fixed it.

I have the same issue but I am using vue.js.
Could you tell me how to fix the bug?

**Comment by Johann-S** [comment]
@sky7st if you can provide a live example using [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link I can help you 😉
