### ISSUE TITLE
Stepper is displayed at step 2

### ISSUE THREAD

**Issue by lcsqlpete** [Johann-S/bs-stepper#58]
If I open my Bootstrap modal containing my stepper, it is positioned at step 1.  If I advance to step 2 then close the modal and open it again, it's displayed with step 2 active, not step 1.

I tried addEventListener for the show.bs-stepper event and issuing stepper.to(1) there, but still no effect.  In fact, show.bs-stepper doesn't seem to fire when the stepper is first opened.

How can I make sure the stepper is displayed with step 1 active?

**Comment by Johann-S** [comment]
If I were you I would listen to `hide.bs.modal` and call `stepper.to(0)`, like that you'll be sure when you reopen your modal your stepper will be at step one.

I hope it can help you 👍

**Comment by lcsqlpete** [comment]
Thanks for the tip, that works.
