### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Johann-S** [Johann-S/bs-stepper#6]
It'll would be awesome if we can make this plugin accessible.

/CC @Lausselloic, and @patrickhlauke if you have time 😄

**Comment by Lausselloic** [comment]
Hello,

I will try to make a PR. But the ideas are : 

1. Use the tabs pattern for accessibility. aria-controls, 
2. Replace links by buttons as they don't go to another page, and set the state disabled on disabled states
3. On non linear stepper add a previous button when previous state is available
