### ISSUE TITLE
Autofocus problem

### ISSUE THREAD

**Issue by lcsqlpete** [Johann-S/bs-stepper#61]
I have the autofocus attribute set on the first input element of the first tab.  When I open the modal containing the stepper, the input is briefly focused but then it disappears.  I also tried using jquery .focus() on the shown.bs-stepper listener but that didn't work either.

Is there something in bs-stepper that would prevent autofocus from working correctly?

**Comment by lcsqlpete** [comment]
I figured out what was happening.  It appears that shown.bs-stepper doesn't fire when the stepper is first displayed so my .focus() wasn't happening on the first tab but does work on the other two tabs.  I got round the issue by issuing .focus() for the first tab in the shown.bs.modal event.

I'm not an expert on this stuff but is there a case for shown.bs-stepper being fired when a stepper is initialized?

**Comment by Johann-S** [comment]
Hi @lcsqlpete,

bs-stepper trigger the shown event on init too, see this CodePen: https://codepen.io/Johann-S/pen/PMzRbw

**Comment by lcsqlpete** [comment]
Thanks, I see the CodePen works.  However, my code doesn't.  Here it is:

<pre>element.addEventListener('shown.bs-stepper', function (event) {
        console.log("index=" + event.detail.indexStep)
        switch (event.detail.indexStep) {
            case 0:
                handleStep_1()
                break
            case 1:
                handleStep_2()
                break
            case 2:
                handleStep_3()
                break
        }
    })</pre>

When I open the page containing the stepper, I don't see anything in the console log; when I go to my second tab, I see "index=1" in the console.log.

Any ideas?

**Comment by Johann-S** [comment]
Maybe you added your listener after the creation of your stepper, you have to add your listener before creating your stepper

**Comment by lcsqlpete** [comment]
Thanks, that fixed it.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by Johann-S** [comment]
You're welcome 👍
