### ISSUE TITLE
Big labels makes screen wider

### ISSUE THREAD

**Issue by alimemonzx** [Johann-S/bs-stepper#66]
Hello,

If you change the name of label 1 2 3. The screen gets an scrollX bar.

for eg: 
1 > Upload Your Documents
2 > Verify Your Documents
3 > Submit Documents

It works good in desktop but ruins the display in mobile

Any help would be appreciated. Thanks for the amazing plugin

**Comment by Johann-S** [comment]
Hi @alimemonzx,

it's recommanded to switch in vertical stepper for mobiles. I hope it'll help you
